# Cloud Build config for the training-job image.
# Used by `make deploy-training-job-local`. See cloudbuild.api.yaml for rationale.

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file=jobs/Dockerfile
      - --tag=${_URI}
      - .
images:
  - ${_URI}

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _URI: ""
